### ISSUE TITLE
Lowercase usage of SYNTAX: words

### ISSUE THREAD

**Issue by samueltardieu** [gifti258/aoc-factor#1]
Hi. I just stumbed on your repo and noticed that you are using lowercase versions of `SYNTAX:` defined words, such as `using:`, `constant:`, instead of `USING:`, `CONSTANT:`, and so on.

Is that on purpose? It won't compile from my (bootstrapped today) Factor listener.

**Comment by gifti258** [comment]
It is very much on purpose and I should probably mention this in the repository description. It is way easier to type for me this way in my keyboard layout and it has been especially comfortable in interactive listener use. My modifications can be found here: gifti258/factor@137b0f82aeefd122903a21e8fdc4b4f8d9bf56a7
